### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by fopina** [fopina/dedofeup#2]
- [ ]  Ability to logout
- [ ]  Previous months (infinite scroll?)
- [ ]  Details button (days balance, etc)
- [ ]  Force refresh in setting dialog (for pwa)
- [ ]  Version function and UI (and display in UI)
